# Document:
# http://simiki.org/docs/configuration.html

url: wiki.yxjxx.com
title: Wiki · yxjxx
keywords: wiki, markdown, linux, python, mac os x, simiki
description: "yxjxx's personal wiki, powered by vim and markdown. Focus on python, Liunx, iOS, and so on."
author: yxjxx
theme: simple
debug: true
